name: Addonresuki
permissions:
  contents: write
on:
  
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 当前仓库
        uses: actions/checkout@v4

      - name: 克隆目标仓库
        run: curl -LSs "https://raw.githubusercontent.com/ReSukiSU/ReSukiSU/main/kernel/setup.sh" | bash
