name: Build-Kernel-ReSukiSU

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      - name: Inject ReSukiSU
        run: |
          curl -LSs -o setup.sh https://raw.githubusercontent.com/ReSukiSU/ReSukiSU/main/kernel/setup.sh
